
name_of_project: 'Laplace'
num_cores: 5 # How many parallel threads for graph creation

extend_grids: True
degree_padding: 0.1 # This region is appended to the lat_range and lon_range values above, and is used as a `padding' region, where we compute travel times, and simulate events in this region, yet train to predict zero for all labels in this area. This way, sources just outside the domain of interest arn't falsely mis-located inside the region (since the model learns what `exterior' events look like, to some extent).
number_of_grids: 5 # Number of distinct spatial graphs to create (this reduced slight bias that can result from only using one spatial graph)
number_of_spatial_nodes: 1250 # 1000 # Number of nodes per spatial graph
n_features: 45
n_cayley: 11

## TRAIN
n_samples: 2000
scale_val: 50000
norm_version: 2
max_val: 0.1
min_val: -3.5
n_ver_save: 1
device: 'cpu' # or 'cpu'

## Graph params
k_spc_edges: 15

## Training params
n_batch: 15
n_epochs: 150000 # add 1, so it saves on last iteration (since it saves every 100 steps)
use_only_complex: False
path_to_data: 'D:/Projects/DeformationEmulators/'
n_ver_load_lh_and_lv_for_training_displacement: 1 ## Trained Lh and Lv model for training displacement model
n_step_load_lh_and_lv_for_training_displacement: 50000

## Application parameters
n_ver_grid: 2 # 1
n_ver_expander_grid: 2 # 1

n_ver_load_displacement: 9 # 8
n_step_load_displacement: 300000 # 149000

n_ver_load_lh_and_lv: 1
n_step_load_lh_and_lv: 50000

n_ver_load_norm: 1
n_step_load_norm: 50000
